export const METHOD = {
  BROWSE:  '@@REACT_REST_METHOD/BROWSE',
  READ:    '@@REACT_REST_METHOD/READ',
  EDIT:    '@@REACT_REST_METHOD/EDIT',
  ADD:     '@@REACT_REST_METHOD/ADD',
  DESTROY: '@@REACT_REST_METHOD/DESTROY',
  REPLACE: '@@REACT_REST_METHOD/REPLACE',
  WIPE:    '@@REACT_REST_METHOD/WIPE',
}

export default {
  METHOD,
}
